AreaOfInterest:
    type: entity
    table: area_of_interest
    fields:
        idAreaofintrest:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_areaofintrest
            generator:
                strategy: IDENTITY
        contentAreaofintrest:
            type: text
            nullable: false
            column: content_areaofintrest
        idUser:
            type: integer
            unsigned: false
            nullable: false
            column: id_user
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
    lifecycleCallbacks: {  }
