Attachments:
    type: entity
    table: attachments
    fields:
        idAttachments:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_attachments
            generator:
                strategy: IDENTITY
        contentAttachments:
            type: text
            nullable: false
            column: content_attachments
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
    lifecycleCallbacks: {  }
