Change:
    type: entity
    table: change
    fields:
        idChange:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_change
            generator:
                strategy: IDENTITY
        changeDate:
            type: date
            nullable: false
            column: change_date
        changeContent:
            type: text
            nullable: false
            column: change_content
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
        idStatus:
            type: integer
            unsigned: false
            nullable: false
            column: id_status
    lifecycleCallbacks: {  }
