Conference:
    type: entity
    table: conference
    fields:
        idConference:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_conference
            generator:
                strategy: IDENTITY
        dateConference:
            type: date
            nullable: false
            column: date_conference
        titleConference:
            type: text
            nullable: false
            column: title_conference
        placeConference:
            type: text
            nullable: false
            column: place_conference
        idUserCd:
            type: integer
            unsigned: false
            nullable: false
            column: id_user_cd
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
        idAuthor:
            type: integer
            unsigned: false
            nullable: false
            column: id_author
    lifecycleCallbacks: {  }
