Editor:
    type: entity
    table: editor
    fields:
        idEditor:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_editor
            generator:
                strategy: IDENTITY
        nameEditor:
            type: integer
            unsigned: false
            nullable: false
            column: name_editor
    lifecycleCallbacks: {  }
