Ereviews:
    type: entity
    table: ereviews
    fields:
        idEreviews:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_ereviews
            generator:
                strategy: IDENTITY
        idPerson:
            type: integer
            unsigned: false
            nullable: false
            column: id_person
        idReview:
            type: integer
            unsigned: false
            nullable: false
            column: id_review
    lifecycleCallbacks: {  }
