Note:
    type: entity
    table: note
    fields:
        idNote:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_note
            generator:
                strategy: IDENTITY
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
        noteContent:
            type: text
            nullable: false
            column: note_content
        idReview:
            type: integer
            unsigned: false
            nullable: false
            column: id_review
        idEditor:
            type: integer
            unsigned: false
            nullable: false
            column: id_editor
    lifecycleCallbacks: {  }
