Reviewer:
    type: entity
    table: reviewer
    fields:
        idReviewer:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_reviewer
            generator:
                strategy: IDENTITY
        idAreaofinterest:
            type: integer
            unsigned: false
            nullable: false
            column: id_areaofinterest
        idEReviewer:
            type: integer
            unsigned: false
            nullable: false
            column: id_e-reviewer
    lifecycleCallbacks: {  }
