ReviewEditor:
    type: entity
    table: review_editor
    fields:
        idRevieweditor:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_revieweditor
            generator:
                strategy: IDENTITY
        send:
            type: boolean
            nullable: false
        inreview:
            type: boolean
            nullable: false
        finished:
            type: boolean
            nullable: false
        idReview:
            type: integer
            unsigned: false
            nullable: false
            column: id_review
    lifecycleCallbacks: {  }
