Role:
    type: entity
    table: role
    fields:
        idRole:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_role
            generator:
                strategy: IDENTITY
        role:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
