Schedule:
    type: entity
    table: schedule
    fields:
        idSchedule:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_schedule
            generator:
                strategy: IDENTITY
        conferenceSchedule:
            type: text
            nullable: false
            column: conference_schedule
    lifecycleCallbacks: {  }
