Speaker:
    type: entity
    table: speaker
    fields:
        idSpeaker:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_speaker
            generator:
                strategy: IDENTITY
        speakerWork:
            type: text
            nullable: false
            column: speaker_work
        speakerName:
            type: text
            nullable: false
            column: speaker_name
        speakerSurname:
            type: text
            nullable: false
            column: speaker_surname
        speakerPlace:
            type: text
            nullable: false
            column: speaker_place
        speakerMail:
            type: text
            nullable: false
            column: speaker_mail
    lifecycleCallbacks: {  }
