SpeakerWork:
    type: entity
    table: speaker_work
    fields:
        idSpeakerWork:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_speaker_work
            generator:
                strategy: IDENTITY
        dateCd:
            type: date
            nullable: false
            column: date_cd
        speakerContentWork:
            type: text
            nullable: false
            column: speaker_content_work
    lifecycleCallbacks: {  }
