UserWork:
    type: entity
    table: user_work
    fields:
        idUserWork:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_user_work
            generator:
                strategy: IDENTITY
        iduser:
            type: integer
            unsigned: false
            nullable: false
            column: idUser
        idWork:
            type: integer
            unsigned: false
            nullable: false
            column: id_work
    lifecycleCallbacks: {  }
